language: go
os:
  - linux

go:
  - 1.11.x

install:
  - go get github.com/stretchr/testify
  - go get github.com/nsf/jsondiff

script:
  - go vet ./...
  - go test -v -coverprofile cover.out -count 1 -failfast -race -bench .